development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  host: localhost
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  host: localhost
  username: myapp
  password: password1
